{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-tunnel-controller.fullname" . }}
  labels:
    {{- include "k8s-tunnel-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  - secrets
  - configmaps
  - services
  - services/status
  - events
  verbs:
  - "*"
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-tunnel-controller.fullname" . }}
  labels:
    {{- include "k8s-tunnel-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-tunnel-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-tunnel-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
