{{- if .Values.token.tokenValue }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-tunnel-controller.secretName" . }}
  labels:
    {{- include "k8s-tunnel-controller.labels" . | nindent 4 }}
spec:
  type: Opaque
  stringData:
    {{ include "k8s-tunnel-controller.tokenKey" . }}: {{ .Values.token.tokenValue }}
{{- end }}
