apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-tunnel-controller.fullname" . }}
  labels:
    {{- include "k8s-tunnel-controller.labels" . | nindent 4 }}
spec:
  type: Opaque
  stringData:
    token: {{ .Values.token }}
