---
name: End to End Tests

on: [push, pull_request]

jobs:
  build:
    name: End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@main
        with:
          version: v0.19.0
          node_image: docker.io/kindest/node:v1.26.4
          kubectl_version: v1.26.4
      - name: End to End Tests
        run: pytest -v tests/e2e.py
